# This role automates the installation instructions here: https://facebook.github.io/react-native/docs/getting-started

- name: install react-native-cli
  command:
    npm install -g react-native-cli

- name: set android studio environment variables
  copy:
    src: android-studio.sh
    dest: /etc/profile.d/

# The android-studio installation does not install the sdkmanager
# Once we have the sdk tools we can automate the below :(
#- name: accept Android SDK licences
#  shell: yes 'y' | /home/{{ user.name }}/Android/Sdk/tools/bin/sdkmanager --licenses

#- name: install react-native Android SDK dependencies
#  command:
#    /home/{{ user.name }}/Android/Sdk/tools/bin/sdkmanager "platform-tools" "platforms;android-23" "add-ons;addon-google_apis-google-23" "sources;android-23"
