
- name: "Install Babel Globally (for Flow)"
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
  with_items:
    - babel-preset-flow
    - babel-cli

- name: "Install nuclide in Atom (for ReactJS development)"
  command: auto-apm -i {{ item }} 
  become: yes
  become_user: "{{ user.name }}"
  with_items:
    - nuclide
    - tool-bar
    - language-babel
