### Create the user and setup its ssh config for vagrant provisioning
- name: create_group
  group:
    name: "{{ user.name }}"

- name: Install package for password generator utility
  apt:
    name: whois
    install_recommends: no

- name: Generate user's default password
  shell: mkpasswd --method=sha-512 {{ user.name }}
  register: default_password
  changed_when: False

- name: create user
  user:
    name: "{{ user.name }}"
    createhome: yes
    skeleton: /etc/skel
    shell: /bin/bash
    group: "{{ user.name }}"
    groups: sudo
    append: yes
    password: "{{ default_password.stdout }}"
    update_password: on_create

- name: Allow password-less sudo for user
  lineinfile:
    path: /etc/sudoers
    line: "{{ user.name }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    create: yes

- name: Create user's bin directory
  file:
    path: "/home/{{ user.name }}/bin"
    state: directory
  become: yes
  become_user: "{{ user.name }}"

- name: create user's .ssh directory
  file:
    path: /home/{{ user.name }}/.ssh
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: u+rwx,og-rwx

# This is so vagrant can provision the VM logging in as this user
- name: copy vagrant ssh keys to user's ssh dir
  copy:
    remote_src: True
    src: /home/vagrant/.ssh/authorized_keys
    dest: /home/{{ user.name }}/.ssh/authorized_keys
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: u+rwx,og-rwx
  when: ansible_kernel is not match(".*Microsoft.*")

### This is to copy user-specific configuration from the host
- name: copy user's ssh dir from host
  copy:
    src: "{{ ssh_config_dir }}"
    dest: /home/{{ user.name }}/.ssh/
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: u+rw,u-x,og-rwx

### To faciliate ssh'ing between VMs
# Note: I tried with authorized_key module and lookup('file', '/home/{{ user.name }}/.ssh/id_rsa.pub')
# but that always failed with file not found error on id_rsa.pub.  There are bug reports about this.
- name: Read user public key
  shell: cat /home/{{ user.name }}/.ssh/id_rsa.pub
  register: public_key

- name: Add user's public key as an authorized key
  lineinfile:
    path: /home/{{ user.name }}/.ssh/authorized_keys
    line: "{{ public_key.stdout }}"
    state: present
    create: yes

# To solve this error with gerrit: Unable to negotiate with legacyhost: no matching key exchange method found.  Their offer: diffie-hellman-group1-sha1
# See http://www.openssh.com/legacy.html
- name: Update ssh config to fix gerrit connection error
  lineinfile:
    path: /home/{{ user.name }}/.ssh/config
    line: "KexAlgorithms +diffie-hellman-group1-sha1"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: u+rw,u-x,og-rwx
    state: present
    create: yes
