go:
  download_location: "https://storage.googleapis.com/golang/{{ go_tarball }}"
  tarball: "go1.11.5.linux-amd64.tar.gz"
  tarball_checksum: "sha256:ff54aafedff961eb94792487e827515da683d61a5f9482f668008832631e5d25"
  version_target: "go version go1.11.5 linux/amd64"
  download_path: "/usr/local/src/" 
  usr_bin_path: "/usr/bin"
  bin_path: "{{ usr_bin_path}}/go/bin"
  set_go_path: true
    