- name: Install hub
  homebrew:
    name: hub
    state: present

# Bash-specific

- name: Setup github token for hub
  lineinfile:
    path: "{{ item.path }}"
    line: "{{ item.line }}"
    regexp: "^.*{{ item.regexp }}\\s*$"
    state: present
    create: yes
  with_items:
    - { regexp: "# github-token", line: "export GITHUB_TOKEN={{ github.access_token }} # github-token", path: "{{ user.home }}/.bash_profile" }
    - { regexp: "# github-token", line: "export GITHUB_TOKEN={{ github.access_token }} # github-token", path: "{{ user.home }}/.zshrc" }
  when: github.access_token != ""

- name: alias git to hub
  lineinfile:
    path: "{{ item.path }}"
    line: "{{ item.line }}"
    regexp: "^.*{{ item.regexp }}\\s*$"
    state: present
    create: yes
  with_items:
    - { regexp: "# hub-alias", line: "alias git=hub # hub-alias", path: "{{ user.home }}/.bash_profile" }
    - { regexp: "# hub-alias", line: "alias git=hub # hub-alias", path: "{{ user.home }}/.zshrc" }
