- name: "Setup Atom PPA"
  shell: |
    curl -sL https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
    sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'
  args:
    chdir: /tmp/

- name: "Update and Upgrade"
  apt: 
    update_cache: yes
    
- name: "Install Atom"
  apt:
    name: atom

