- name: Add kubernetes apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add kubernetes ppa
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install kubectl
  apt:
    name: [ "kubectl={{ kubectl_version }}", "bash-completion" ]
    update_cache: yes
    install_recommends: no
    force: yes # required to allow for version downgrades

- name: Set kubectl bash completion for user
  lineinfile:
    path: "{{ user.home }}/.bashrc"
    line: "{{ item }}"
    state: present
    create: yes
  with_items:
    - source <(kubectl completion bash)
  become: yes
  become_user: "{{ user.name }}"

# Setup KUBECONFIG management.
- name: Create kube config dir
  file:
    dest: "{{ user.home }}/.kube/configs"
    state: directory
  become: yes
  become_user: "{{ user.name }}"

- name: Install kube config management script
  copy:
    src: "setup-kubeconfig.sh"
    dest: "/usr/local/bin/"

- name: Setup kube config management script in startup script
  lineinfile:
    path: "{{ user.home }}/.bashrc"
    line: "{{ item }}"
    regexp: '^.*# setup-kubeconfig\s*$'
    state: present
    create: yes
  with_items:
    - "[[ -f \"/usr/local/bin/setup-kubeconfig.sh\" ]] && . \"/usr/local/bin/setup-kubeconfig.sh\" # setup-kubeconfig"
  become: yes
  become_user: "{{ user.name }}"
