- name: Create useful links in user's home
  file:
    src: "{{ item.src }}"
    dest: "{{ user.home }}/{{ item.dest }}"
    state: link
  with_items:
    - { src: "/mnt/c/Users/{{ user.name }}", dest: "winhome" }
    - { src: "/mnt/c/Users/{{ user.name }}/OneDrive", dest: "onedrive" }
  become: yes
  become_user: "{{ user.name }}"
    
- name: Setup /etc/wsl.conf
  copy:
    src: wsl.conf
    dest: /etc/wsl.conf

- name: Install vagrant plugins
  shell: vagrant plugin install vagrant-vbguest vagrant-disksize
  become: yes
  become_user: "{{ user.name }}"
